import sys
sys.path.append('/home/ishu/Documents/res-work/prams/pram/src')
print(sys.path)
from pram.data   import GroupSizeProbe, ProbeMsgMode
from pram.entity import Group, GroupQry, GroupSplitSpec, Site
from pram.rule   import GoToRule, DiscreteInvMarkovChain, TimeInt, Rule
from pram.sim    import Simulation


class Autogenerated1(Rule):
	def apply(self, pop, group, iter, t):
		
		if group.has_attr({'income': 'l'}):
			if group.has_attr({'flu': 'S'}): return [GroupSplitSpec(p= 0.8980891719745223, attr_set={ 'flu': 'S' }),GroupSplitSpec(p= 0.10100090991810737, attr_set={ 'flu': 'I' }),]

		if group.has_attr({'income': 'l'}):
			if group.has_attr({'flu': 'R'}): return [GroupSplitSpec(p= 0.774390243902439, attr_set={ 'flu': 'R' }),GroupSplitSpec(p= 0.22560975609756098, attr_set={ 'flu': 'S' }),]

		if group.has_attr({'income': 'l'}):
			if group.has_attr({'flu': 'I'}): return [GroupSplitSpec(p= 0.7286063569682152, attr_set={ 'flu': 'I' }),GroupSplitSpec(p= 0.2713936430317848, attr_set={ 'flu': 'R' }),]

		if group.has_attr({'income': 'm'}):
			if group.has_attr({'flu': 'S'}): return [GroupSplitSpec(p= 0.9439480097481722, attr_set={ 'flu': 'S' }),GroupSplitSpec(p= 0.05523964256701868, attr_set={ 'flu': 'I' }),]

		if group.has_attr({'income': 'm'}):
			if group.has_attr({'flu': 'R'}): return [GroupSplitSpec(p= 0.8912, attr_set={ 'flu': 'R' }),GroupSplitSpec(p= 0.1088, attr_set={ 'flu': 'S' }),]

		if group.has_attr({'income': 'm'}):
			if group.has_attr({'flu': 'I'}): return [GroupSplitSpec(p= 0.5277777777777778, attr_set={ 'flu': 'I' }),GroupSplitSpec(p= 0.4722222222222222, attr_set={ 'flu': 'R' }),]
