from pram.data import GroupSizeProbe, ProbeMsgMode
from pram.entity import Group, GroupQry, GroupSplitSpec, Site
from pram.rule import GoToRule, DiscreteInvMarkovChain, TimeInt, Rule
from pram.sim import Simulation


class Autogenerated1(Rule):
    def apply(self, pop, group, iter, t):

        if group.has_attr({'flu': 'R'}): return [GroupSplitSpec(p=0.6897905759162304, attr_set={'flu': 'R'}),
                                                 GroupSplitSpec(p=0.3102094240837696, attr_set={'flu': 'S'}), ]

        if group.has_attr({'flu': 'S'}): return [GroupSplitSpec(p=0.6788124156545209, attr_set={'flu': 'S'}),
                                                 GroupSplitSpec(p=0.32118758434547906, attr_set={'flu': 'I'}), ]

        if group.has_attr({'flu': 'I'}): return [GroupSplitSpec(p=0.5191919191919192, attr_set={'flu': 'I'}),
                                                 GroupSplitSpec(p=0.47878787878787876, attr_set={'flu': 'R'}), ]
