from pram.data   import GroupSizeProbe, ProbeMsgMode
from pram.entity import Group, GroupQry, GroupSplitSpec, Site
from pram.rule   import GoToRule, DiscreteInvMarkovChain, TimeInt, Rule
from pram.sim    import Simulation


class Autogenerated1(Rule):
	def apply(self, pop, group, iter, t):
		
		if group.has_attr({'flu': 'R'}): return [GroupSplitSpec(p= 0.7046035805626598, attr_set={ 'flu': 'R' }),GroupSplitSpec(p= 0.29411764705882354, attr_set={ 'flu': 'S' }),]

		if group.has_attr({'flu': 'S'}): return [GroupSplitSpec(p= 0.6890982503364738, attr_set={ 'flu': 'S' }),GroupSplitSpec(p= 0.31090174966352624, attr_set={ 'flu': 'I' }),]

		if group.has_attr({'flu': 'I'}): return [GroupSplitSpec(p= 0.5136842105263157, attr_set={ 'flu': 'I' }),GroupSplitSpec(p= 0.4863157894736842, attr_set={ 'flu': 'R' }),]
