from pram.data   import GroupSizeProbe, ProbeMsgMode
from pram.entity import Group, GroupQry, GroupSplitSpec, Site
from pram.rule   import GoToRule, DiscreteInvMarkovChain, TimeInt, Rule
from pram.sim    import Simulation


class Autogenerated0(Rule):
	def apply(self, pop, group, iter, t):
		
		if group.has_attr({'flu': 'S'}): return [GroupSplitSpec(p= 0.8998354102986127, attr_set={ 'flu': 'S' }),GroupSplitSpec(p= 0.10016458970138725, attr_set={ 'flu': 'I' }),]

		if group.has_attr({'flu': 'R'}): return [GroupSplitSpec(p= 0.8866116582379558, attr_set={ 'flu': 'R' }),GroupSplitSpec(p= 0.11312217194570136, attr_set={ 'flu': 'S' }),]

		if group.has_attr({'flu': 'I'}): return [GroupSplitSpec(p= 0.7857142857142857, attr_set={ 'flu': 'I' }),GroupSplitSpec(p= 0.21428571428571427, attr_set={ 'flu': 'R' }),]
