from pram.data   import GroupSizeProbe, ProbeMsgMode
from pram.entity import Group, GroupQry, GroupSplitSpec, Site
from pram.rule   import GoToRule, DiscreteInvMarkovChain, TimeInt, Rule
from pram.sim    import Simulation


class Autogenerated1(Rule):
	def apply(self, pop, group, iter, t):
		
		if group.has_attr({'flu': 'S'}): return [GroupSplitSpec(p= 0.7999059487420644, attr_set={ 'loc': 'school' }),GroupSplitSpec(p= 0.20009405125793558, attr_set={ 'loc': 'home' }),]

		if group.has_attr({'flu': 'R'}): return [GroupSplitSpec(p= 0.8959552953698776, attr_set={ 'loc': 'home' }),GroupSplitSpec(p= 0.1040447046301224, attr_set={ 'loc': 'school' }),]

		if group.has_attr({'flu': 'I'}): return [GroupSplitSpec(p= 0.49748490945674045, attr_set={ 'loc': 'school' }),GroupSplitSpec(p= 0.5025150905432596, attr_set={ 'loc': 'home' }),]
