import sys
sys.path.append('/home/ishu/Documents/res-work/prams/pram/src')
# print(sys.path)
from pram.data   import GroupSizeProbe, ProbeMsgMode
from pram.entity import Group, GroupQry
from pram.sim    import Simulation
from Autogenerated1 import Autogenerated1
def sim02(iter_cnt):
    sim = (
        Simulation().
        add([
            Autogenerated1(),
            GroupSizeProbe.by_attr('flu', 'flu', ['S', 'I', 'R'], msg_mode=ProbeMsgMode.CUMUL),
            Group(m=500, attr={ 'income': 'l' }),
            Group(m=500, attr={ 'income': 'm' })
        ]).
        run(iter_cnt)
    )
    print(sim.probes[0].get_msg())
    print()

def sim03(iter_cnt):
    sim = (
        Simulation().
        add([
            Autogenerated1(),
            GroupSizeProbe(
                'flu-income',
                [
                    GroupQry(attr={ 'income': 'l', 'flu': 'S' }),
                    GroupQry(attr={ 'income': 'l', 'flu': 'I' }),
                    GroupQry(attr={ 'income': 'l', 'flu': 'R' }),
                    GroupQry(attr={ 'income': 'm', 'flu': 'S' }),
                    GroupQry(attr={ 'income': 'm', 'flu': 'I' }),
                    GroupQry(attr={ 'income': 'm', 'flu': 'R' })
                ],
                msg_mode=ProbeMsgMode.CUMUL,
            ),
            Group(m=500, attr={ 'income': 'l','flu': 'S' }),
            Group(m=500, attr={ 'income': 'm' ,'flu': 'S'})
        ]).
        run(iter_cnt)
    )
    print(sim.probes[0].get_msg())
    print()
actual_rule_path = r'/home/ishu/Documents/res-work/prams/pram/src/sim/04-flu-prog-02-income/sim.py'
print('Rule is taken from path',actual_rule_path)
iter_cnt = 64
sim02(iter_cnt)
sim03(iter_cnt)


# 15  flu-income: (0.27 0.10 0.12 0.31 0.04 0.16 )   (  273.6   102.8   123.6   306.0    36.3   157.7 )   [1000.0]
